#!/usr/bin/env bash

CSSEDIR=${1:-../COVID-19}

set -o nounset
set -o errexit

git -C "$CSSEDIR" fetch
git -C "$CSSEDIR" pull

python3 covid.py > graph.html

git add graph.html
git commit -m "Graph as of CSSE commit $(git -C "$CSSEDIR" rev-parse HEAD^{commit})"

git push